config/routes.rb
CourseAvailability::Application.routes.draw do
  root :to => 'course_pages#home'
  
  resources :course_pages
  resources :searches
  resources :sessions, only: [:new, :create, :destroy]
  resources :trackings
  resources :users
  
  get '/course_list', to: 'course_pages#course_list', via: [:get]
  get '/signup', to: 'users#new', via: [:get, :post]
  get '/signin', to: 'sessions#new', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: 'delete'
  
  get '/help', to: 'course_pages#help', via: [:get]

  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  created_at      :datetime
#  updated_at      :datetime
#  name            :text
#  email           :text
#  password_digest :text
#  remember_token  :string(255)
#  frequency_value :integer
#  frequency       :text
#
# Based heavily on the User model in the Ruby on Rails tutorial by Michael Hartl at:
# http://ruby.railstutorial.org/
#
# Author: Hansen Cheng
#         Branden Ogata
#

class User < ActiveRecord::Base
  has_secure_password
  
  before_save {|user| user.email = email.downcase}
  before_create :create_remember_token
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, presence: true
  validates :email, presence: true,
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true, on: :create, length: {minimum: 6}
  validates :password_confirmation, presence: true, on: :create
  validates :frequency_value, numericality: {greater_than: 0}

  #
  # Generates a new security token for a user.
  #
  # Returns:
  #   The new security token.
  #
  # Author: Branden Ogata
  #

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  #
  # Encrypts a security token for secure transfer.
  #
  # Parameters:
  #   token    The token to encrypt.
  #
  # Returns:
  #   The encrypted token.
  #
  # Author: Branden Ogata
  #

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  

  private
  
    #
    # Generates and stores a new security token for this User.
    #
    # Author: Branden Ogata
    #
    
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
    
    #
    # Calculates the next time to send emails to this User.
    #
    # Ultimately not used in this project.
    #
    # Author: Hansen Cheng
    #
    
    def calculate_next_time(person) 	
    end
end

app/controllers/users_controller.rb
#
# The users controller.
#
# Based heavily on the User controller in the Ruby on Rails tutorial by Michael Hartl at:
# http://ruby.railstutorial.org/
#
# Author: Hansen Cheng
#         Branden Ogata
#

class UsersController < ApplicationController
  include ActionView::Helpers::TextHelper
  before_filter :signed_in_user, only: [:edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update, :destroy]
  
  #
  # The user creation page.
  #
  # Author: Branden Ogata
  #
  
  def new
    if signed_in?
      redirect_to root_path
    else
      @user = User.new
    end  
  end
  
  #
  # Creates a new user.
  #
  # Author: Hansen Cheng
  #         Branden Ogata
  #
  
  def create
    if signed_in?
      redirect_to root_path
    else
      @user = User.new(user_params)
      @user.frequency = "min"
      @user.frequency_value = 1;
      
      if @user.save
        sign_in @user
        flash[:success] = "Welcome to the Course Availability Tool!"
        CourseMailer.welcome_email(@user).deliver
        redirect_to @user
      else
        error_message = "#{pluralize(@user.errors.count, 'error')}: <br />"
        @user.errors.full_messages.each {|e| error_message += "#{e} <br />"}
        flash.now[:error] = error_message.html_safe
        render 'new'
      end
    end
  end
  
  #
  # The profile page for the user.
  #
  # Author: Hansen Cheng
  #         Branden Ogata
  #
  
  def show
    @user = User.find(params[:id])
    @trackings = Tracking.where(user_id: @user.id)
  end
  
  #
  # The settings page for the user.
  #
  # The methods in the sessions helper mean that nothing needs to be set up here.
  #
  # Author: Branden Ogata
  #
  
  def edit
  end
  
  #
  # Updates user information.
  #
  # Author: Branden Ogata
  #
  
  def update
    for p in params[:user]
      puts p
    end
    
    if current_user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      # Currently disabled while developers test an alternate solution using initializers
#      perform(@user)
      redirect_to @user
    else
      error_message = "Error when updating user information:<br />"
      current_user.errors.full_messages.each {|e| error_message += "#{e}<br />"}
      flash.now[:error] = error_message.html_safe;
      render 'edit'
    end
  end
  
  #
  # Deletes a user account.
  #
  # Author: Branden Ogata
  #
  
  def destroy
    User.find(params[:id]).delete
    Tracking.where(user_id: params[:id]).delete_all
    flash[:success] = "Deleted account"
    redirect_to root_path
  end
  
  private
  
    #
    # Verifies that this user is the correct user.
    #
    # Author: Branden Ogata
    #
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    #
    # The list of available user fields.
    #
    # Author: Branden Ogata
    # 
    
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :frequency, :frequency_value)
    end
end

app/helpers/users_helper.rb
#
# Methods to help with user operations, particularly in sending notification emails.
#
# Author: Hansen Cheng
#         Branden Ogata
#

module UsersHelper
  # 
  # This method accepts a input of a user variable and obtains the
  # frequency value and the frequency e.g. daily, min, or hr.
  # 
  # Based on the frequency it uses a scheduler to send out emails.
  #
  # As of now it sends email based on frequency, but not based on
  # if the seats have been deducted.
  #
  # Parameters:
  #   user    The User to create a Rufus task for.
  #
  # Author: Hansen Cheng
  #
    
	def perform(user)
		@user = user
		@frequent_value = @user.frequency_value
		@frequent = @user.frequency
		scheduler = Rufus::Scheduler.new
		
		#Initial idea of testing if it is daily selection
		if @frequent == 'day'
			
			scheduler.every(@frequent_value.to_s() + "d") do
				CourseMailer.notify_email(@user).deliver
		   	end
		# Minute selection
		elsif @frequent == 'min'
		    
			scheduler.every(@frequent_value.to_s() + "m") do
				CourseMailer.notify_email(@user).deliver
			end
		# Hour selection
		elsif @frequent == 'hr'
			
			scheduler.every(@frequent_value.to_s() + "h") do
				CourseMailer.notify_email(@user).deliver
			end
		end
		
	end
	
	#
	# Returns an array containing courses to send notifications for.
	#
	# There are two possible cases where it is necessary to send a message to the user:
	# when seats become available (zero seats to non-zero seats) and
	# when seats become completely filled (non-zero seats to zero seats).
	# All other changes are irrelevant.
	#
	# This method has the side effect of updating the Course table with the new number of seats
	# regardless of whether any courses are returned.
	#
	# Parameters:
	#   user    The User whose courses to check.
	#
	# Returns:
	#   An array containing Course instances to send notifications for.
	#
	# Author: Branden Ogata
	#
	
  def courses_to_email(user)
    courses = []
    
    # For each course that the user is tracking
    Tracking.where(user_id: user.id).each do |t|
      course = Course.find(t.course_id)
      seats = course.seats
      
      # Check the UH Course Availability site for an updated seat count
      url = "https://www.sis.hawaii.edu/uhdad/avail.classes?i=MAN&t=201430&s=#{course.name[0..course.name.index(' ')]}"
      page = Nokogiri::HTML(open(url)).css('table.listOfClasses')
      
      match = page.css("tr").select {|tr| tr.content.include?(course.name) &&
                                          tr.content.include?("%03d" % course.section)}.first
      current_seats = match.css("td")[7].text.to_i
      puts "Course #{course.name + '-' + ("%03d" % course.section)}: #{seats} seats to #{current_seats} seats"
      
      # If transition between zero and non-zero, then send email
      if (seats != current_seats) && ((seats == 0) || (current_seats == 0))
        courses.push course
      end
      
      # Update the Course in the database
      course.seats = current_seats.to_i
      course.save
    end
    
    puts "Courses: #{courses}"
    return courses
  end
end

app/views/users/_multiline_course_cell.html.erb
<!--
  Breaks text into two lines.
  
  This is used for table entries that take two rows, such as the room of courses with labs,
  where the lecture room is on one row and the lab room is on the next.  Actually creating two rows
  would create an additional border though (as shown in the course list page), which is not
  aesthetically pleasing and makes it more difficult to visually group the lecture and lab
  together.  For that reason, this adds a line break to replace the newline, keeping the field in
  one table row but on separate lines.
  
  Author: Branden Ogata
-->

<% if field.include?("\n") %>
  <%= field[0 ... field.index("\n")] %><br />
  <%= field[field.index("\n") + 1 ... field.length] %>
<% else %>
  <%= field %>
<% end %>

app/views/users/_user_fields.html.erb
<!--
  The fields in which to input user data.
  
  Author: Branden Ogata
-->

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

<input name="authenticity_token" 
       type="hidden" 
       value="<%= form_authenticity_token %>"/>

app/views/users/edit.html.erb
<% provide(:title, "Edit Account") %>

<!--
  The Settings page where users can edit their account information.
  
  Author: Hansen Cheng
          Branden Ogata
-->

<div class="row">
  <div>
    <%= form_for(@user) do |f| %>
      <%= render 'user_fields', f: f %><br/>
      
      <%= label_tag 'frequency', 'Frequency Value' %>
      <!-- Text field for the user to enter a value for the frequency to send out the email -->
      <%= f.text_field :frequency_value , :placeholder => "Please enter a value" %>
      
      <%= label_tag 'time', 'Time Frame' %>
      <!-- Drop down menu for user to select the time to send out email. E.g. hr, min etc -->
      <%= f.select(:frequency, options_for_select(["day", "hr", "min"], @user.frequency),
      														:prompt => 'Select a time frame') %>
      
      <%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
  <%= link_to "Delete your account", @user, method: :delete,
              data: {confirm: "Are you sure you want to permanently delete your account?"} %>  
</div>

app/views/users/new.html.erb
<% provide(:title, "Create Account") %>

<!--
  The Create Account page where new users can create an account.
  
  Author: Branden Ogata
-->

<div class="row">
  <div>
    <%= form_for(@user) do |f| %>
      <%= render 'user_fields', f: f %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<!--
  The Profile page.
  
  This displays the courses that the user is tracking and contains drop-down menus through which
  to track courses.
  
  Author: Hansen Cheng
          Branden Ogata
-->

<!-- Get the departments and courses for JavaScript to use later -->
<% courses = get_test_courses() %>
<%= javascript_tag do %>
  setCourseData(<%= raw ['ICS', 'MATH', 'PSY'].to_json%>, <%= raw courses.to_json %>);
<% end %>

<div class="row">
  <h1><%= @user.name %></h1>
  
  <%= form_tag trackings_path do %>
    <input name="authenticity_token" 
           type="hidden" 
           value="<%= form_authenticity_token %>"/>    
    <h2>Tracking Courses:</h2>
    <table border="1">
      <tr>
        <th>CRN</th>
        <th>Course</th>
        <th>Section</th>
        <th>Title</th>
        <th>Credits</th>
        <th>Instructor</th>
        <th>Seats Available</th>
        <th>Days</th>
        <th>Time</th>
        <th>Room</th>
        <th>Dates</th>
      </tr>
      <% @trackings.each do |t| %>
        <tr>
          <% course = Course.find(t.course_id) %>
          
          <td>
            <%= course.crn %>
          </td>
          <td>
            <%= course.name %>
          </td>
          <td>
            <%= "%03d" % course.section %>
          </td>
          <td>
            <%= render 'multiline_course_cell', field: course.title %>
          </td>
          <td>
            <%= course.credits %>
          </td>
          <td>
            <%= course.instructor %>
          </td>
          <td>
            <%= course.seats %>
          </td>
          <td>
            <%= render 'multiline_course_cell', field: course.days %>
          </td>
          <td>
            <%= render 'multiline_course_cell', field: course.time %>
          </td>
          <td>
            <%= render 'multiline_course_cell', field: course.room %>
          </td>
          <td>
            <%= render 'multiline_course_cell', field: course.dates %>
          </td>
          <td>
            <%= link_to 'Remove', t, method: 'delete' %>
          </td>
        </tr>
      <% end %>
    </table>
    
    <div id="add-new-courses">
      <h3>Add Course:</h3>
        Department: <%= select_tag 'department', nil, onchange: 'updateCourses()' %><br />
        Course: <%= select_tag 'course' %><br />
        <%= submit_tag 'Add' %>
    </div>
  <% end %>
</div>