config/routes.rb
CourseAvailability::Application.routes.draw do
  root :to => 'course_pages#home'
  
  resources :course_pages
  resources :searches
  resources :sessions, only: [:new, :create, :destroy]
  resources :trackings
  resources :users
  
  get '/course_list', to: 'course_pages#course_list', via: [:get]
  get '/signup', to: 'users#new', via: [:get, :post]
  get '/signin', to: 'sessions#new', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: 'delete'
  
  get '/help', to: 'course_pages#help', via: [:get]

  

end

app/views/layouts/_header.html.erb
<!--
  The navbar for this application.
	
	This is displayed on every page of the website and provides consistent navigation.
  
  Author: Hansen Cheng
          Branden Ogata
-->  

<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<nav>
				<%= link_to "Course Availability", :root, id: "logo" %>
				<div class="search">
					<%# search field %>
					<%= form_tag searches_path do %>
						<%= text_field_tag :search %>
				    <input name="authenticity_token" 
						    	 type="hidden" 
							     value="<%= form_authenticity_token %>"/>						
						<%= submit_tag "Search" %>
					<% end %>
				</div>
				<ul class="nav pull-right">
					<li><%=link_to "Home", :root %></li>
					<li><%=link_to "Course List", course_list_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Profile", current_user %></li>
						<li><%= link_to "Settings", edit_user_path(current_user) %></li>
						<li><%= link_to "Sign out", :signout, method: 'delete' %></li>
					<% else %>
						<li><%=link_to "Sign in", :signin %></li>
					<% end %>
					<li><%=link_to "Help", help_path %></li>

				</ul>	
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--
  Imports code for the shim.
  
  Branden does not know what a shim is and should not be the one writing the documentation for this.
  
  Author: Hansen Cheng
-->

<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!--
  The basic framework for all pages in this application.
	
	This loads in all of the stylesheets and JavaScript code used across the site.
	The body then renders the header and content for the current page.
  
  Author: Hansen Cheng
          Branden Ogata
-->  

<html>
<head>
	<title><%=yield(:title)%></title>
	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
  <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js"></script>	
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>	
		<%= yield %>
	</div>
</body>
</html>